### ISSUE TITLE
allowedHeaders configuration doesn't change

### ISSUE THREAD

**Issue by Emanuel-Palestino** [leafsphp/cors#4]
Hi, I changed the cors config file in LEAF API with the following:
```
'methods' => 'GET,PUT,POST,DELETE,OPTIONS',
'allowedHeaders' => 'Content-Type,Authorization',
'credentials' => true,

/* ... Other default configuration */
```

But the Access-Control-Allow-Headers header in preflight request doesn't change, it always has '*' value (default configuration).

This is the response headers:
![image](https://github.com/leafsphp/cors/assets/75344407/ca590062-9839-42ec-b088-151868dff549)

I'm changing the default configuration for use cookies, I don't know if there is other way.

I hope you can help me, thanks.

**Comment by mychidarko** [comment]
I'll check on this issue @Emanuel-Palestino

**Comment by mychidarko** [comment]
I just released a new version that should fix the issue
