### ISSUE TITLE
preg_match throwing error in CORS module

### ISSUE THREAD

**Issue by skverma618** [leafsphp/cors#5]
## CORS code

`app()->cors([
    "origin"               => 'http://example.com',
    "optionsSuccessStatus" => 200 // some legacy browsers (IE11, various SmartTVs) choke on 204
]);`

## Screenshot
![Screenshot 2023-07-29 152329](https://github.com/leafsphp/docs/assets/55022564/07038f6a-b636-49e0-9ca9-9fc0a61e9b06)

**Comment by mychidarko** [comment]
Hi @skverma618 can I see that section of your code?

**Comment by phederal** [comment]
@mychidarko The error appears if you open config/cors.php (MVC) and set origin => '*' to "/\.example2\.com$/"

**Comment by mychidarko** [comment]
I just released a new version that should fix the issue
